### ISSUE TITLE
Errors serializing custom events

### ISSUE THREAD

**Issue by coladarci** [newrelic/elixir_agent#266]
**Describe the bug**
We have error spam from timeouts; probably 10 to 20 a day. Not a fire, but it's been consistent for many months now. Here's the stack trace:
```
Protocol.UndefinedError: protocol Jason.Encoder not implemented for {:error, :timeout} of type Tuple, Jason.Encoder protocol must always be explicitly implemented. This protocol is implemented for the following type(s): Scorpion.Snapshots.Time, Scorpion.Snapshots.TimeDuration, Scorpion.Snapshots.Provider, Scorpion.Actor.Client, Scorpion.Actor.Device, Scorpion.Actor.OS, Scorpion.Actor, Scorpion.Snapshots.TicketQuantity, Scorpion.Snapshots.Activity, Money, Cldr.LanguageTag, Ecto.Association.NotLoaded, Ecto.Schema.Metadata, Any, Map, Float, NaiveDateTime, List, DateTime, Atom, Integer, BitString, Date, Jason.Fragment, Decimal, Time
  File "lib/jason.ex", line 150, in Jason.encode!/2
  File "lib/new_relic/util/http.ex", line 17, in NewRelic.Util.HTTP.post/3
  File "lib/new_relic/harvest/collector/protocol.ex", line 58, in NewRelic.Harvest.Collector.Protocol.issue_call/2
  File "lib/new_relic/harvest/collector/protocol.ex", line 50, in NewRelic.Harvest.Collector.Protocol.call_remote/3
  File "lib/new_relic/harvest/collector/custom_event/harvester.ex", line 92, in NewRelic.Harvest.Collector.CustomEvent.Harvester.send_harvest/1
  File "lib/new_relic/harvest/collector/custom_event/harvester.ex", line 66, in NewRelic.Harvest.Collector.CustomEvent.Harvester.handle_call/3
  File "gen_server.erl", line 706, in :gen_server.try_handle_call/4
  File "gen_server.erl", line 735, in :gen_server.handle_msg/6
```

Is this just expected behavior or is there something more concerning here about how consistently calls to new relic are timing out?

Thanks!

**Environment**
* Elixir & Erlang version: `1.10.4`
* Agent version: `1.19.5`

**Comment by binaryseed** [comment]
Actually, this doesn't look like a timeout talking _to_ New Relic.

I believe it's an error being encountered trying to serialize a custom event which contains a tuple value (`{:error, :timeout}`) in the payload... There are protections in place for this but something might be leaking through, I'll take a look...

**Comment by coladarci** [comment]
Ah you're probably right - I'm going to dig deeper on my end. The context here is that I'm getting crushed by a lot of errors like these. At the same time this one comes in, too:
```
Jason.EncodeError: invalid byte 0x83 in <<67, 76, 73, 69, 78, 84, 32, 82, 69, 80, 76, 89, 32, 79, 70, 70, 59, 32, 83, 69, 84, 32, 103, 50, 48, 65, 65, 65, 65, 83, 99, 71, 86, 121, 99, 50, 108, 122, 100, 71, 86, 117, 100, 70, 57, 122, 90, 88, 78, 122, ...>>
  File "lib/jason.ex", line 150, in Jason.encode!/2
  File "lib/new_relic/util/http.ex", line 17, in NewRelic.Util.HTTP.post/3
  File "lib/new_relic/harvest/collector/protocol.ex", line 58, in NewRelic.Harvest.Collector.Protocol.issue_call/2
  File "lib/new_relic/harvest/collector/protocol.ex", line 50, in NewRelic.Harvest.Collector.Protocol.call_remote/3
  File "lib/new_relic/harvest/collector/span_event/harvester.ex", line 128, in NewRelic.Harvest.Collector.SpanEvent.Harvester.send_harvest/1
  File "lib/new_relic/harvest/collector/span_event/harvester.ex", line 109, in NewRelic.Harvest.Collector.SpanEvent.Harvester.handle_call/3
  File "gen_server.erl", line 706, in :gen_server.try_handle_call/4
  File "gen_server.erl", line 735, in :gen_server.handle_msg/6
```

It's like something in the stack is dumping bad data somewhere that new relic is picking up?

**Comment by binaryseed** [comment]
Could be attributes that you are adding... I have a fix for the Custom Event errors coming...

**Comment by binaryseed** [comment]
https://github.com/newrelic/elixir_agent/pull/267

**Comment by coladarci** [comment]
We aren't adding any custom attributes; I believe this is just picking up this stuff on it's own via the Logs, maybe? All we are using is `NewRelic.Tracer` and `NewRelic.Phoenix.Transaction` perhaps one of those is adding what you are describing.

**Comment by binaryseed** [comment]
Fixes released in `v1.19.6`, please let us know if something else arises...

**Comment by coladarci** [comment]
@binaryseed I'm still seeing that second error from above, I'm happy to open a separate issue:
```
Jason.EncodeError: invalid byte 0x83 in <<67, 76, 73, 69, 78, 84, 32, 82, 69, 80, 76, 89, 32, 79, 70, 70, 59, 32, 83, 69, 84, 32, 103, 50, 48, 65, 65, 65, 65, 76, 89, 51, 74, 108, 90, 71, 86, 117, 100, 71, 108, 104, 98, 72, 77, 58, 103, 50, 48, 65, ...>>
  File "lib/jason.ex", line 150, in Jason.encode!/2
  File "lib/new_relic/util/http.ex", line 17, in NewRelic.Util.HTTP.post/3
  File "lib/new_relic/harvest/collector/protocol.ex", line 58, in NewRelic.Harvest.Collector.Protocol.issue_call/2
  File "lib/new_relic/harvest/collector/protocol.ex", line 50, in NewRelic.Harvest.Collector.Protocol.call_remote/3
  File "lib/new_relic/harvest/collector/transaction_trace/harvester.ex", line 102, in NewRelic.Harvest.Collector.TransactionTrace.Harvester.send_harvest/1
  File "lib/new_relic/harvest/collector/transaction_trace/harvester.ex", line 59, in NewRelic.Harvest.Collector.TransactionTrace.Harvester.handle_call/3
  File "gen_server.erl", line 706, in :gen_server.try_handle_call/4
  File "gen_server.erl", line 735, in :gen_server.handle_msg/6
```

While I agree this is clearly not a problem w/ new relic, the fact that it bombs if someone sends bad data in feels a little wrong; I am not doing anything custom, I have removed all tracing (that was a theory I had since I'm tracing something that uses Redix) and this happens every few minutes, so I'm just sort of at a loss for where to even go from here to debug this further. 

Any thoughts?

**Comment by mathiasose** [comment]
After we upgraded `new_relic_agent` we're getting *a lot* of `(ArgumentError) cannot convert the given list to a string.`.

It seems that the fix just pushed the problem further down the line. If `Jason.encode(body)` fails, then interpolating `body` into `"Unable to JSON encode: #{body}"` can also fail.

Not sure what the correct solution is. Maybe not interpolating body at all, maybe do it in a `try-rescue`?

**Comment by binaryseed** [comment]
Yeah, this should clear that up: https://github.com/newrelic/elixir_agent/pull/315

Do you have any idea what kind of bad data is winding up in there?

**Comment by mathiasose** [comment]
That was quick!

> Do you have any idea what kind of bad data is winding up in there?

Still trying to figure that out. I think it's payloads from the redis instrumentation that look something like this:
```
[48, 50, "Datastore/operation/Redis/SET", %{host: "sage.redis.dev.private", operation: "SET", port_path_or_id: "6379", sql: <<83, 69, 84, 32, 95, 104, 101, 97, 108, 116, 104, ...>>}, [], ":\"Elixir.SageWeb.Cache.0\" sage.redis.dev.private:6379", nil]
```

It seems that `List.to_string` neither likes maps, nor nil values.

**Comment by binaryseed** [comment]
hmm, that `sql` attribute is suspect, let me dig in

**Comment by mathiasose** [comment]
I can't quite figure it out, because all the logs I have are truncated. I tried to grab the payloads from the logs and replace the `...` bits, but `Jason.encode` seems happy to encode those. If #315 gets released and I'm able to find the debug events in the web view I might be able to find more data?

**Comment by binaryseed** [comment]
Published `1.23.5`, let me know what you find...

**Comment by mathiasose** [comment]
I'm not able to find any events in the web view of the type `NewRelic.log(:debug, "Unable to JSON encode: #{inspect(body)}") `. So either they're not being sent, or they're not being shown because of log levels? I can't find any documentation about configuring log levels.

I did however find the `new_relic.log` from running the app locally, and it has some interesting entries that look something like
```
[DEBUG] - 2021-02-03 12:37:17 - Bad attribute value: :"db.statement" => <<83, 69, 84, 32, 47, 97, 112, 105, 47, 95, 105, 110, 116, 101, 114, 110, 97, 108, 47, 115, 116, 97, 116, 115, 47, 112, 108, 97, 116, 102, 111, 114, 109, 47, 115, 101, 115, 115, 105, 111, 110, 115, 47, 99, 104, 97, 116, 115, 47, 116, ...>>
```

This binary sequence is the (truncated) text `SET /api/_internal/stats/platform/sessions/chats/t...`, which is a redis command to set a value (the URL bit is part of a redis key). So I'm not definitely sure, but I suspect this is related.

**Comment by binaryseed** [comment]
Yeah, probably related.. there must be something about that command string that is invalid, i suspect that debug line is coming from here:

https://github.com/newrelic/elixir_agent/blob/master/lib/new_relic/util.ex#L76

Probably this bad string value is winding up in the transaction trace itself and causing the failure to JSON encode. Any way you can think of that would cause invalid unicode to wind up in there? Any chance the code slicing up the bytes of the string? I've seen multi-byte unicode chars get sliced & become invalid, for example.

I think I can address this w/o knowing the root cause but it would help for a repro test...

**Comment by mathiasose** [comment]
The values are inserted to Redis by Nebulex (v1.1, not the most recent, https://hexdocs.pm/nebulex/1.1.1/Nebulex.Cache.html#c:set/3).

When the data is handed over to the cache (`Cache.set(data)`), `data` is a native Elixir data structure (a map or a list usually). I'm not sure what serialization Nebulex does before the data enters Redis, if any. I guess it might just be inserting the raw byte sequence representing the data? Which Redis can handle I think, but there's not guarantee it's a valid JSON string?

**Comment by binaryseed** [comment]
Oh, yes well if it's just trying to put bytes in there then yes that could cause some problems! I'll see if I can make a quick tweak to use the same attribute processing in the location where the encode errors happened...

**Comment by binaryseed** [comment]
I pushed a patch version `1.23.6` that will hopefully ensure the failures don't happen, mind trying that out?
